package coupon.system.core.dao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;

import coupon.system.core.beans.Company;
import coupon.system.core.db.ConnectionPool;
import coupon.system.core.exceptions.CouponSystemException;

public class CompanyDaoDb implements CompanyDao {

	@Override
	public int addCompany(Company company) throws CouponSystemException {
		// get a connection from the pool
		Connection con = ConnectionPool.getInstance().getConnection();
		// set the SQL command as a String
		String sql = "insert into company values(0, ?, ?, ?)";
		// create a statement object to execute the SQL command
		try (PreparedStatement pstmt = con.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);) {
			pstmt.setString(1, company.getName());
			pstmt.setString(2, company.getEmail());
			pstmt.setString(3, company.getPassword());
			pstmt.executeUpdate(); // the company goes to the database
			// now we want to know the id generated for the company:
			ResultSet rs = pstmt.getGeneratedKeys();
			rs.next();
			int autoGeneratedId = rs.getInt(1);
			company.setId(autoGeneratedId);
			return autoGeneratedId; // return the auto generated id
		} catch (SQLException e) {
			throw new CouponSystemException("createCompany failed", e);
		} finally {
			ConnectionPool.getInstance().restoreConnection(con);
		}
	}

	@Override
	public void updateCompany(Company company) throws CouponSystemException {
		Connection con = ConnectionPool.getInstance().getConnection();
		String sql = "update company set name=?, email=?, password=? where id=?";
		try (PreparedStatement pstmt = con.prepareStatement(sql);) {
			pstmt.setString(1, company.getName());
			pstmt.setString(2, company.getEmail());
			pstmt.setString(3, company.getPassword());
			pstmt.setInt(4, company.getId());
			int rowCount = pstmt.executeUpdate();
			if (rowCount == 0) {
				throw new CouponSystemException("updateCompany faild. company id " + company.getId() + " not found");
			}
		} catch (SQLException e) {
			throw new CouponSystemException("updateCompany failed", e);
		} finally {
			ConnectionPool.getInstance().restoreConnection(con);
		}
	}

	@Override
	public boolean isCompanyExist(String email, String password) throws CouponSystemException {
		// TODO Auto-generated method stub
		return false;
	}

	@Override
	public void deleteCompany(int companyId) throws CouponSystemException {
		// TODO Auto-generated method stub

	}

	@Override
	public List<Company> getAllCompanies() throws CouponSystemException {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public Company getOneCompany() throws CouponSystemException {
		// TODO Auto-generated method stub
		return null;
	}

}
