package coupon.system.core.dao;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import coupon.system.core.beans.Coupon;
import coupon.system.core.db.ConnectionPool;
import coupon.system.core.exceptions.CouponSystemException;

public class CouponDaoDb implements CouponDao {

	@Override
	public int createCoupon(Coupon coupon) throws CouponSystemException {
		// get a connection from the pool
		Connection con = ConnectionPool.getInstance().getConnection();
		// set the SQL command as a String
		String sql = "insert into coupon values(0, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
		// create a statement object to execute the SQL command
		try (PreparedStatement pstmt = con.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);) {
			pstmt.setInt(1, coupon.getCompanyId());
			pstmt.setInt(2, coupon.getCategory().ordinal());
			pstmt.setString(3, coupon.getTitle());
			pstmt.setString(4, coupon.getDescription());
			// when adding a coupon convert the LocalDate to java.sql.Date
			pstmt.setDate(5, Date.valueOf(coupon.getStartDate()));
			pstmt.setDate(6, Date.valueOf(coupon.getEndDate()));
			pstmt.setInt(7, coupon.getAmount());
			pstmt.setDouble(8, coupon.getPrice());
			pstmt.setString(9, coupon.getImage());
			pstmt.executeUpdate(); // the coupon goes to the database
			// now we want to know the id generated for the coupon:
			ResultSet rs = pstmt.getGeneratedKeys();
			rs.next();
			int autoGeneratedId = rs.getInt(1);
			coupon.setId(autoGeneratedId);
			return autoGeneratedId; // return the auto generated id
		} catch (SQLException e) {
			throw new CouponSystemException("createCoupon failed", e);
		} finally {
			ConnectionPool.getInstance().restoreConnection(con);
		}
	}

}
